In [1]:
import numpy as np
from arqtic import program, hamiltonians, QITE

In [2]:
#define system variables
N = 1 #number of qubits
Jz = -1/np.sqrt(2) #ising interaction strength
mu_x = -Jz #transverse magnetic field strength
param_free_ham = hamiltonians.Ising_Hamiltonian(N, Jz, [mu_x, 0, 0]) #parameter-free Hamiltonian
#ising_ham0 = hamiltonians.Ising_Hamiltonian(N, Jz, [0.01, 0, 0]) #Hamiltonian at beginning of parameter sweep

#define simulation variables
#tau = 1 #total trajectory time to evolve lambda from 0 to 1
#dtau = 1.0 #time-step for trajectory
#num_steps = int(tau/dtau)
#T = 10 #total number of trajectories
#dt =  dtau #timestep for Trotter approximation: setting equal to dtau means one trotter-step per time-step in evolution
#lamba_protocol = np.linspace((dtau/tau),1.0,num_steps)
#dldt = 0.1 # d(lambda)/d(tau)
#shots = 1000

#define QITE variables
beta = 2.0 #inverse temperature of systems
dbeta = 0.5 #step-size in beta for QITE
domain = 1 #domain of opertators for QITE

In [3]:
prog = program.Program(N)
#Testing QITE
#measured_metts_state = program.random_bitstring(N)
#print(measured_metts_state)
psi0 = [1,0]
prog.make_QITE_prog(param_free_ham, beta, dbeta, domain, psi0, 1.0)


H is:  [[[0], [0, 0.7071067811865475, 0, 0]]]
0
exp_values is:  [1.0, 0.0, 0j, 1.0]
norm is:  (1.0606601717798212+0j)
Smat is:  [[2. 0. 0. 2.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [2. 0. 0. 2.]]
bvec is:  [ 0.          0.         -0.66666667  0.        ]
x is:  [-0.    -0.     0.332 -0.   ]
psi is:  [ 0.94539237+0.j -0.32593446+0.j]
1
exp_values is:  [(0.9999999999999999+0j), (-0.6162719075445701+0j), 0j, (0.787533450699954+0j)]
norm is:  (1.249307826310047+0j)
Smat is:  [[ 2.         -1.23254382  0.          1.5750669 ]
 [-1.23254382  2.          0.          0.        ]
 [ 0.          0.          2.         -0.        ]
 [ 1.5750669   0.          0.          2.        ]]
bvec is:  [ 0.          0.         -0.44574302  0.        ]
x is:  [-0.         -0.          0.22153818 -0.        ]
psi is:  [ 0.85066983+0.j -0.52570033+0.j]
2
exp_values is:  [(1+0j), (-0.8943948262845495+0j), 0j, (0.44727831907597576+0j)]
norm is:  (1.3256819553437276+0j)
Smat is:  [[ 2.         -1.78878965  0.         